/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.materiotrack.views;

import com.mycompany.materiotrack.controllers.MaterialController;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author blackheart
 */
public class MainView extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private JPanel contentPanel;
    private JButton currentNavButton;

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setupUI();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

       
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Stock Management");
        setSize(800, 600);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());

       

        // Main content panel with CardLayout
        cardLayout = new CardLayout();
        contentPanel = new JPanel(cardLayout);
        add(contentPanel, BorderLayout.CENTER);

        // Adding placeholder sections
        

        pack();
        setVisible(true);
    }

    private void setupUI() {
        setTitle("MaterioTrack - Material Management System");
        setSize(1200, 800);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        // Main container with BorderLayout
        setLayout(new BorderLayout());
        
        // Create sidebar
        JPanel sidebar = createSidebar();
        add(sidebar, BorderLayout.WEST);
        
        // Create main content area
        contentPanel = new JPanel(new CardLayout());
        add(contentPanel, BorderLayout.CENTER);
        
        // Initialize panels
        initContentPanels();
    }

    private JPanel createSidebar() {
        JPanel sidebar = new JPanel();
        sidebar.setBackground(new Color(45, 45, 45));
        sidebar.setPreferredSize(new Dimension(250, 0));
        sidebar.setLayout(new GridLayout(0, 1, 0, 10));
        
        String[] sections = {
            "📦 Materials", 
            "🏗️ Projects", 
            "📦 Stock", 
            "🏭 Suppliers", 
            "📝 Orders", 
            "📊 Reports"
        };

        for (String section : sections) {
            JButton btn = createNavButton(section);
            btn.addActionListener(new NavButtonListener(section.replaceAll("[^a-zA-Z]", "").toUpperCase()));
            sidebar.add(btn);
        }
        
        return sidebar;
    }

    private JButton createNavButton(String text) {
        JButton btn = new JButton(text);
        btn.setFont(new Font("Segoe UI", Font.PLAIN, 16));
        btn.setForeground(Color.WHITE);
        btn.setBackground(new Color(60, 60, 60));
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
        btn.setHorizontalAlignment(SwingConstants.LEFT);
        btn.setPreferredSize(new Dimension(250, 60));
        btn.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        return btn;
    }
       MaterialController controller = new MaterialController();


    private void initContentPanels() {
        contentPanel.add(new MaterialsPanel(controller), "MATERIALS");
        contentPanel.add(new ProjectsPanel(), "PROJECTS");
        contentPanel.add(new StockPanel(), "STOCK");
        contentPanel.add(new SuppliersPanel(), "SUPPLIERS");
        contentPanel.add(new OrdersPanel(), "ORDERS");
        contentPanel.add(new ReportsPanel(), "REPORTS");
    }

    private class ToolbarActionListener implements ActionListener {
        private final String section;

        public ToolbarActionListener(String section) {
            this.section = section;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            cardLayout.show(contentPanel, section);
        }
    }

    private class NavButtonListener implements ActionListener {
        private final String panelName;

        public NavButtonListener(String panelName) {
            this.panelName = panelName;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            if (currentNavButton != null) {
                currentNavButton.setBackground(new Color(60, 60, 60));
            }
            currentNavButton = (JButton) e.getSource();
            currentNavButton.setBackground(new Color(0, 102, 204));
            
            CardLayout cl = (CardLayout) contentPanel.getLayout();
            cl.show(contentPanel, panelName);
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
